# Site settings
title: X home
header-img: img/home-bg.jpg
email: diyselfway@gmail.com
description: "Android developer"
baseurl: ""
url: "http://diyselfway.github.io"

# SNS settings
RSS: true
weibo_username:     diyselfway
zhihu_username:     diyselfway
github_username:    diyselfway
#twitter_username:  diyselfway
#facebook_username:  diyselfway

# Build settings
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

anchorjs: true      # if you want to customize anchor. check out line:129 of `post.html`

# Markdown settings
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# use Github Flavored Markdown !important
markdown: kramdown
kramdown:
  input: GFM 

# Duoshuo settings
# please set your own DuoShuo account in `post.html` and `about.html`
useDuoshuo: true    # use both Comment and Share
useShare: true      # use Comment only. seeing the Share component is depend on Comment so we can NOT use share only.

# Todo: Analysis settings
# Please set your own analysis account in `head.html`(Baidu) and `default.html`(QQ)
useBaiduAnalysis: false
useTencentAnalysis: false
useGoogleAnalysis: false


# Sidebar settings
sidebar: true
sidebar-feature-tags: true
sidebar-about-description: "一个不务正业的家伙，现在在自学Android开发。"
sidebar-avatar: /img/avatar-julian.jpg     # use absolute URL.

# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me/"
    },
    {
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },
    {
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    }
]