# Site settings
title: X home
header-img: img/home-bg.jpg
email: diyselfway@gmail.com
description: "Android developer"
baseurl: ""
url: "http://diyselfway.github.io"

# SNS settings
RSS: false
#twitter_username: diyselfway
github_username:  diyselfway
#facebook_username:  diyselfway
weibo_username: diyselfway
zhihu_username: diyselfway

# Build settings
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Markdown settings
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible, so I switch to kramdown
markdown: kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# use Github Flavored Markdown !important
kramdown:
  input: GFM

# Duoshuo settings
# Please set your own DuoShuo account.
useDuoshuo: true    # Comment and Share
useShare: true      # use Comment only. seeing the Share component is depend on Comment so we can NOT use share only.


# Todo: Analysis settings
# Please set your own analysis account
useBaiduAnalysis: false
useTencentAnalysis: false
useGoogleAnalysis: false
